services:
  - type: web
    name: forex-signals-backend
    env: node
    rootDir: backend    # This tells Render to look in the backend directory
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1 